name: store_aziz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  layout: ^1.0.3
  phlox_drawer: ^1.0.0
  # google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.2.1
  fading_images_slider: ^0.0.4
  get: ^4.6.5
  badges: ^2.0.3
  coverflow: ^2.0.3
  outline_search_bar: ^2.3.0
  
  hovering: ^1.0.4
  flutter_swiper_null_safety: ^1.0.2
  url_launcher: ^6.1.7
  mailto: ^2.0.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cdn/
